### ISSUE TITLE
`package.authors` will be deprecated

### ISSUE THREAD

**Issue by qryxip** [qryxip/cargo-equip#120]
https://github.com/rust-lang/rfcs/pull/3052

> The `package.authors` field could be deprecated and removed in a future

> `cargo init` will stop pre-populating the field when running the command, and it will not include the field at all in the default `Cargo.toml`. Crate authors will still be able to manually include the field before publishing if they so choose.

> # Drawbacks

> This RFC will make it harder for third-party tools to query the author information of crates published to crates.io.

> By design, this RFC discourages adding the metadata allowing to know historical crate authors and makes it harder to retrieve it. In some cases, crate authors may have wanted that information preserved. After this RFC, crate authors who want to display historical authors who are not current crate owners will have to present that information in some other way.

**Comment by qryxip** [comment]
マジでどうしようか

**Comment by msdrigg** [comment]
Currently this cargo command will fail when authors are present. Can you switch to just stripping the authors from the cargo.toml?

This will make it possible to use external crates without having to fork and manually remove authors.
