### ISSUE TITLE
Attempting to install from master fails

### ISSUE THREAD

**Issue by msdrigg** [qryxip/cargo-equip#158]
If I run the command in your readme to install from master

    cargo install --git https://github.com/qryxip/cargo-equip

 it fails with the error: 

> error: multiple packages with binaries found: cargo-equip, solutions

**Comment by qryxip** [comment]
I've forgotten to update the README when I added `solutions`.

You can specify the `cargo-equip` package with:

```console
❯ cargo install cargo-equip --git https://github.com/qryxip/cargo-equip
```

**Comment by msdrigg** [comment]
That worked, thank you
